stages:
  - build
  - package
  - test
before_script:
  - export PATH=$PATH:/usr/bin:/etc/docker
variables:
  IMAGE_NAME: "cicd-backend"
gradle-build:
  image: java:8-jdk
  stage: build
  only:
    - mj_test
    - tags
  script:
    - export GRADLE_USER_HOME=pwd/.gradle
    - chmod +x gradlew
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  tags:
    - docker
unitTests:
  stage: test
  image: java:8-jdk
  only:
    - tags
  script:
    - export GRADLE_USER_HOME=pwd/.gradle
    - chmod +x gradlew
    - ./gradlew assemble
    - ./gradlew test
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  tags:
    - docker
docker-build:
  stage: package
  only:
    - tags
  script:
    - envsubst '${IMAGE_NAME} ${CI_COMMIT_TAG}' <backend-template.yml
    - echo ${CI_COMMIT_TAG}
    - echo ${ttest}
    - docker info
    - docker build -t [IP]/${IMAGE_NAME}:${CI_COMMIT_TAG} .
    - docker login -u  -p  [IP]
    - docker push wapl-math.220.90.208.8.nip.io:443/${IMAGE_NAME}:${CI_COMMIT_TAG}
    - kubectl get deployments 
    - envsubst '${IMAGE_NAME} ${CI_COMMIT_TAG}' <backend-template.yml | kubectl apply -f -
    - kubectl apply -f backend-instance.yml 
  tags:
    - shell

after_script:
  - echo "End CI"
